Ajout page contact
WildCodeSchool-2024-02/php-p2-straszik pull request #10
Opened 2024-04-23 13:13 UTC by anaelwn

Yazu confirme mon pull request stp

2024-04-23 13:23 UTC, Niko3727 approved these changes

2024-04-23 13:24 UTC, MatthWCS approved these changes

2024-04-23 13:24 UTC, MatthWCS commented on database.sql
> +)
le petit ; à la fin de la ligne

2024-04-23 14:15 UTC, yavuzkutuk approved these changes

2024-04-23 14:16 UTC, yavuzkutuk commented
@anaelwn juste a réglé le petit ; à la fin de la ligne 62 de ton fichier database.sql

2024-04-23 14:25 UTC, Julio-Compressor requested changes
revoir le CSS pour les appels de balises pour ne pasa generer de conflit css

2024-04-23 14:25 UTC, Julio-Compressor commented on public/assets/css/contact.css
> +form {
ne pas mettre des champs direct comme ça dans ton css, plutot mettre : " .class form {"

2024-04-23 15:35 UTC, anaelwn commented on public/assets/css/contact.css
> +form {
C'est réglé normalement

2024-04-23 15:35 UTC, anaelwn commented on database.sql
> +)
C'est réglé

2024-04-23 15:45 UTC, Julio-Compressor approved these changes

2024-04-24 06:54 UTC, vravanel approved these changes

2024-04-24 06:54 UTC, vravanel commented on src/View/Contact/show.html.twig
> +
Attention y'a beaucoup lignes vides

2024-04-24 06:54 UTC, merged